### ISSUE TITLE
Event Attendance

### ISSUE THREAD

**Issue by ml0130** [MikeRomaa/zhuartcc.org#12]
In conjunction with the event score can we also get either a slider bar or a dropdown menu to keep track of attendance. We can talk details at a later date if and how it will affect the overall scores.

**Comment by ml0130** [comment]
This might be easier if we have the user link their TS UUID to the site. then all the events team needs to do is press a button to do the attendance cheek. Then allow us to double check the check before counting toward the event score.

**Comment by MikeRomaa** [comment]
I think a roll call on a simple google doc would be better than storing the attendance on the actual website. We can't expect everyone to link their UUID and theres no real point in storing that archaically.
