### ISSUE TITLE
Event Score Borked

### ISSUE THREAD

**Issue by GabrielHogan** [MikeRomaa/zhuartcc.org#15]
**Describe the bug**
Read the title....

**To Reproduce**
1. Control for longer than the event
2. Check event score
3. Notice a 0 hours controlled for the event which your controlled longer than the actual time
4. Cry
5. Notify WebTeam
6. WebTeam fix because the way events score is calculated is broken.

**Additional context**
/events/score/<user-cid>

**Comment by MikeRomaa** [comment]
Resolved by commit dccebc6c12886756c5b36ce44118636cb43d285b.
