### ISSUE TITLE
Manual name assignment to event position

### ISSUE THREAD

**Issue by ml0130** [MikeRomaa/zhuartcc.org#2]
`For the purpose of ACE Team members. Can we get the option to add a user that's part of ACE Team to a position if they are unable to sign up?

**Comment by MikeRomaa** [comment]
Why not leave positions blank so people can sign up last minute? ACE Team doesnt need to be given a score or anything so no real use of adding them.

**Comment by ml0130** [comment]
The reason why so as we fill positions with ACE other controllers know the position is filled. Or an option to mark the position as filed.

**Comment by MikeRomaa** [comment]
But isn't the whole point of the ACE team is to be a _backup_ if the position doesn't get filled? So if a home controller becomes available and wants to sign up like 2 hours before the event they can.

**Comment by ml0130** [comment]
True but then we run into the problem of members thinking that there are still positions open when that might not be the case.
