### ISSUE TITLE
API for The Marvelous Mr Masiel

### ISSUE THREAD

**Issue by rcharper100** [MikeRomaa/zhuartcc.org#31]
**Is your feature request related to a problem? Please describe.**
Makes an API
**Describe the solution you'd like**
Romashov Give Jarid a Backend login
**Describe alternatives you've considered**
N/A (Can't think of much else)
**Additional context**

**Comment by MikeRomaa** [comment]
I already told you, I'd make it after you submit the pull request for the actual information you want him to access. When creating user accounts I select what they can and cannot see and I need the model to exist first.

**Comment by MikeRomaa** [comment]
Got him set up with an account.
