### ISSUE TITLE
Blank sheet when not in full screen

### ISSUE THREAD

**Issue by KG4HDQ** [MikeRomaa/zhuartcc.org#5]
**Describe the bug**
When looking at the ZHU site, and the window is NOT in full screen, to click on the lines on the upper right corner the screen goes to a blank sheet and you see nothing.

**To Reproduce**
1. Go to ZHU site in full screen mode, then restore down (when it says in chrome) or get out of full screen.
2. Click on The three lines on the upper right corner, presumably to open a drop down menu. 
3. Scroll down to. No need to. 
4. See error: You should see nothing.  

**Expected behavior**
Full screen you see the options. Not full screen, blank sheet.

**Screenshots**
![ZHU](https://user-images.githubusercontent.com/71995054/94382647-23acf800-0103-11eb-9318-d514541ac3c4.jpg)

**Desktop (please complete the following information):**
 - OS: WIN 7 HP
 - Browser Chrome
 - Version Version 85.0.4183.121 (Official Build) (64-bit)

**Additional context**

**Comment by MikeRomaa** [comment]
This is a know issue. I just didn't finish the mobile nav menu. Thanks for reporting tho :)

**Comment by KG4HDQ** [comment]
Ok. Not a problem!
