### ISSUE TITLE
Event Submunition for Support

### ISSUE THREAD

**Issue by ml0130** [MikeRomaa/zhuartcc.org#51]
To eliminate VA's emailing us with the bare minimum. Could we get away on the site for these groups to submit their requests on the website. Once the group submits the request it's then up to a member of the events team to accept the request or not. Then upon accepting the request it auto-fill the new event creation window with the info given from the group then all the events team needs to do fill in the needed positions.

Here is the following info they need to provide. Event name, description, banner, requested fields, VA/Group name

**Comment by MikeRomaa** [comment]
Will be included in [Houston-ARTCC/zhu-core](https://github.com/Houston-ARTCC/zhu-core).
