### ISSUE TITLE
Can't View and sign via mobile phone. 

### ISSUE THREAD

**Issue by KG4HDQ** [MikeRomaa/zhuartcc.org#54]
Are we working on a mobile acceptable site?  Kind of previous when I reported about seeing the site when in a smaller window,  I tried to look at the site on my phone, but get a blank page with a "X". 

![Screenshot_20210105-081335_Chrome](https://user-images.githubusercontent.com/71995054/103715446-42cee780-4f86-11eb-9ffc-6c72d3999e1f.jpg)
![Screenshot_20210105-080555_Chrome](https://user-images.githubusercontent.com/71995054/103715455-48c4c880-4f86-11eb-8f99-c082b8f6e935.jpg)

**Comment by MikeRomaa** [comment]
Implemented in https://github.com/Houston-ARTCC/zhu-frontend.
