### ISSUE TITLE
Reformatting Event Signups

### ISSUE THREAD

**Issue by ml0130** [MikeRomaa/zhuartcc.org#55]
As events, we would like the signup system to be reformated to allow for shift-based signups. In reference to the screenshots, we would like to have the position signups simplify them. In the sense of how ZMP has theirs where the user signs up for the position type. This for sifts we like how LA does theirs. so overall what we would like to see is from the user's side that only see the amount of that potioning type that is available. then from the staff side, we see what the actual positions are being offered and who signed up for what position type, and what times the user signed up for.

ZMP Poistions: ![image](https://user-images.githubusercontent.com/27445711/103722386-ad7f2380-4f84-11eb-802d-752a089a843e.png)

LA Shifts: 
![image](https://user-images.githubusercontent.com/27445711/103724639-a9093980-4f89-11eb-8b06-7a672e940cb1.png)

**Comment by MikeRomaa** [comment]
Implemented in https://github.com/Houston-ARTCC/zhu-core.
