### ISSUE TITLE
Drop down option

### ISSUE THREAD

**Issue by ml0130** [MikeRomaa/zhuartcc.org#9]
![image](https://user-images.githubusercontent.com/27445711/96410536-ee447900-119b-11eb-8014-364971e2ebe0.png)
![image](https://user-images.githubusercontent.com/27445711/96410671-1df38100-119c-11eb-8f84-7ea72be5a31e.png)

There seems to be a visualization problem with the drop-down menus on both Event Creation and Manual Position Assignment. Not fully sure if it has something to do with the current theme of the site or not.

**Comment by MikeRomaa** [comment]
Was resolved with a previous commit. You probably just needed to clear cached css files.
